apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "postgresql-service"
  DB_PORT: "5433"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
